---
apiVersion: v1
kind: Namespace
metadata:
  name: galactic-mqtt

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: galactic-mqtt-config
  namespace: galactic-mqtt
  labels:
    app: galactic-mqtt
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: galactic-mqtt
  namespace: galactic-mqtt
  labels:
    app: galactic-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galactic-mqtt
  template:
    metadata:
      labels:
        app: galactic-mqtt
    spec:
      containers:
      - name: galactic-mqtt
        image: eclipse-mosquitto:latest
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: config
        configMap:
          name: galactic-mqtt-config

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: galactic-mqtt
  labels:
    app: mqtt
spec:
  type: ClusterIP
  selector:
    app: galactic-mqtt
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
    name: mqtt

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-nodeport
  namespace: galactic-mqtt
  labels:
    app: mqtt
spec:
  type: NodePort
  selector:
    app: galactic-mqtt
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 31883
    protocol: TCP
    name: mqtt
